#!/usr/bin/env python3
"""Emit the people-ascii runtime into the lightfeather-rebrand-next worktree:

  public/people-ascii/{Stem}.mp4       the 9 finals clips (432x454 crf20)
  src/lib/people-ascii/engine.js       render_core JS_CORE verbatim + exports
  src/lib/people-ascii/engine.d.ts     minimal typings for the engine
  src/lib/people-ascii/clips.ts        STEMS / CLIPS(+baked bg) / BASE /
                                       PER_VIDEO / DURS / END_AUTO from
                                       Marco's merged finals

Source of truth stays in LF-Website/.tmp/people-ascii-mockup (render_core.py
+ lf-select-final-merged-*.json). Re-run this after any engine change or a
new finals merge, then rebuild the site.

Usage: python3 gen_site_assets.py /path/to/lf-next-worktree
"""
import json
import pathlib
import shutil
import subprocess
import sys

import render_core as rc

HERE = pathlib.Path(__file__).parent
WT = pathlib.Path(sys.argv[1]).resolve()
assert (WT / "src").is_dir(), f"{WT} does not look like the site repo"

rc.CLIPS_DIR = pathlib.Path("/Users/marcoopertti/LF-Website/quality_test_outputs/nv2select")
# Display order (Marco 7-27: Sarah first). perVideo is keyed by NAME, so
# order here is presentation-only.
STEMS = ["Sarah", "Marco", "Nate", "Ruben", "Sheelagh", "Isaiah", "Ryan",
         "Morgan", "Shelley"]

FINALS = json.loads((HERE / "lf-select-final-merged-20260727-1212.json").read_text())
assert sorted(FINALS["stems"]) == sorted(STEMS), "finals stems must match STEMS"

END_AUTO = 6.5


def duration(stem: str) -> float:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-select_streams", "v:0",
         "-show_entries", "stream=duration", "-of", "csv=p=0",
         str(rc.CLIPS_DIR / f"{stem}.mp4")],
        check=True, capture_output=True, text=True).stdout
    return float(out.strip().rstrip(","))


# ---- clips: copy mp4s + bake the background grids --------------------------
pub = WT / "public" / "people-ascii"
pub.mkdir(parents=True, exist_ok=True)
clips, durs = [], {}
for stem in STEMS:
    src = rc.CLIPS_DIR / f"{stem}.mp4"
    shutil.copy2(src, pub / f"{stem}.mp4")
    bg, bgw, bgh = rc.bake_bgmax(src)
    clips.append({"src": f"/people-ascii/{stem}.mp4", "bg": bg, "bgw": bgw,
                  "bgh": bgh, "zones": rc.ZONES.get(stem, []),
                  "wr": stem in rc.WALL_RULE,
                  "mg": rc.MARGINS.get(stem, 0.18)})
    durs[stem] = round(duration(stem), 2)

lib = WT / "src" / "lib" / "people-ascii"
lib.mkdir(parents=True, exist_ok=True)

# ---- engine.js: JS_CORE verbatim ------------------------------------------
(lib / "engine.js").write_text(
    "/* AUTO-GENERATED from LF-Website/.tmp/people-ascii-mockup/render_core.py\n"
    "   (JS_CORE) by gen_site_assets.py - DO NOT EDIT, regenerate instead.\n"
    "   Client-only: creates canvases at module scope, so import it\n"
    "   dynamically from inside an effect, never at module top level. */\n"
    "/* eslint-disable */\n"
    + rc.JS_CORE
    + "\nexport { initTile, sizeTile, resetTone, renderTile };\n")

(lib / "engine.d.ts").write_text("""\
/** Hand-written typings for the generated engine.js (people-ascii core). */
export interface EngineTile {
  clip: unknown;
  c: HTMLCanvasElement;
  ctx: CanvasRenderingContext2D;
  src: HTMLVideoElement;
  ready: boolean;
  [k: string]: unknown;
}
export function initTile(
  clip: unknown,
  c: HTMLCanvasElement,
  srcEl: HTMLVideoElement
): EngineTile;
export function sizeTile(t: EngineTile): void;
export function resetTone(t: EngineTile): void;
export function renderTile(t: EngineTile, settings: Record<string, unknown>): void;
""")

# ---- clips.ts ---------------------------------------------------------------
base = dict(FINALS["settings"]["global"])
pv = FINALS["settings"]["perVideo"]
(lib / "clips.ts").write_text(
    "/* AUTO-GENERATED by LF-Website/.tmp/people-ascii-mockup/gen_site_assets.py\n"
    "   from Marco's merged finals ("
    + FINALS["saved"] + ") - DO NOT EDIT, regenerate instead. */\n\n"
    "export type AsciiSettings = Record<string, number | string>;\n\n"
    "export interface AsciiClip {\n"
    "  src: string;\n"
    "  bg: string;   // base64 baked per-cell max-luma grid (bgw x bgh)\n"
    "  bgw: number;\n"
    "  bgh: number;\n"
    "  zones: number[][];\n"
    "  wr: boolean;\n"
    "  mg: number;\n"
    "}\n\n"
    f"export const STEMS: string[] = {json.dumps(STEMS)};\n\n"
    f"export const CLIPS: AsciiClip[] = {json.dumps(clips)};\n\n"
    f"export const BASE: AsciiSettings = {json.dumps(base)};\n\n"
    "export const PER_VIDEO: Record<string, AsciiSettings> = "
    f"{json.dumps(pv)};\n\n"
    f"export const DURS: Record<string, number> = {json.dumps(durs)};\n\n"
    f"export const END_AUTO = {END_AUTO};\n")

total = sum((pub / f"{s}.mp4").stat().st_size for s in STEMS)
print(f"wrote {len(STEMS)} clips ({total/1048576:.1f} MB) + engine.js + clips.ts -> {WT}")
